### ISSUE TITLE
Cheating gravity

### ISSUE THREAD

**Issue by TurriJP** [MarmotaGames/aracnotopia#6]
If you are hanging from the web and keep holding left or right, the spider will como to equilibrium at an angle from the expected vertical position. The spider needs to be pulled back towards this vertical direction when it reaches the extremes of pendular movement, even if the player is holding the directional keys

**Comment by TurriJP** [comment]
Incidentally, the spider has a tendency to settle down slightly to the right of the normal. I'm guessing this has to do with whatever Godot uses to calculate mass - collision shape, or something else - not being entirely symmetrical in the spider

UPDATE: Final resting angle does not depend on length of web. If you stretch after reaching a rest situation, the spider will initially be pulled by gravity as it should, but then will slowly gravitate towards the same angle of rest
![equilibrio3](https://user-images.githubusercontent.com/42307219/48083223-c7bdeb00-e1db-11e8-8d66-eaae7e87d493.png)
![equilibrio3b](https://user-images.githubusercontent.com/42307219/48083224-c8568180-e1db-11e8-9efc-3c60abab36ac.png)
![equilibrio3c](https://user-images.githubusercontent.com/42307219/48083225-c8568180-e1db-11e8-86c4-7ae110716dda.png)

**Comment by TurriJP** [comment]
UPDATE: spamming the buttons to "cheat gravity" no longer works. However, the spider still comes to rest at weird angles. It seems that this behavior has to with the fact that web+spider are a system, so it comes to rest at a position that seems unnatural to us

**Comment by EduYukio** [comment]
The gravity cheating got fixed. The other issue relating to the web not stading on the vertical got a individual issue post.
