### ISSUE TITLE
Should you be able to attach anywhere?

### ISSUE THREAD

**Issue by TurriJP** [MarmotaGames/aracnotopia#9]
Right now the web can only attach to the stones. There are two other behaviors that could/should be implemented:

1) Attaching to any solid surface. One way to maybe build this on top of existing functionality would be to create a very small area at the mouse location, and use it to check for contact with the web
2) Attaching in place. The purpose for this would be so that you can immediately (and safely) drop down (i.e. abseiling/"rapel")

**Comment by EduYukio** [comment]
Moved to trello.
